version: "3.8"

services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DBURL: jdbc:postgresql://ep-old-sun-a2wvmb5k.eu-central-1.pg.koyeb.app:5432/koyebdb
      DBUSERNAME: koyeb-adm
      DBPASSWORD: npg_SK2cabTzEtV4
